development:
  adapter: postgresql
  encoding: unicode
  database: biblioteca_development
  pool: 5
  username: postgres
  password: postgres
  
test:
  adapter: postgresql
  encoding: unicode
  database: biblioteca_test
  pool: 5
  username: postgres
  password: postgres

